[package]
name = "mpr"
version = "0.3.3"
authors = ["Hunter Wittenborn <hunter@hunterwittenborn.com"]
description = "The official command-line interface for the makedeb Package Repository"
edition = "2021"

[dependencies]
bat = "0.21.0"
ansi_term = "0.12.1"
chrono = "0.4.19"
clap = { version = "3.2.8", features = ["cargo", "env"] }
dirs = "4.0.0"
edit = "0.1.4"
exitcode = "1.1.2"
flate2 = "1.0.24"
quit = "1.1.4"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
tempfile = "3.3.0"
